services:
  postgres-enterprise:
    image: postgres:15
    container_name: postgres-enterprise
    environment:
      POSTGRES_DB: enterprise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_enterprise_data:/var/lib/postgresql/data

volumes:
  postgres_enterprise_data:

networks:
  default:
    name: microservices-network
    driver: bridge
